### ISSUE TITLE
Order Confirmed:   Make delay 3 seconds (current transition is too fast)

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#83] opened 2019-03-23 00:07 UTC

**Comment by kevinp** [comment] 2019-03-23 09:25
@siegel86 , as you add issues please assign to the Project that we want it completed in.  Dunk Test Invitation Email is the first milestone.  If it has to be completed by that time assign it there, otherwise leave it unassigned, or assign to another project.

**Comment by kevinp** [comment] 2019-03-23 09:34
Closed as duplicate of #81

**Comment by siegel86** [comment] 2019-03-24 16:12
glitch with the "hang tight" wheel.  after order is checked out from phone and confirmed on the tablet, the hang tight wheel spins.  Needs to fix so no "hang tight" and after order is checked out there is just a 3 second delay and goes to next screen.

**Comment by danipralea** [comment] 2019-03-25 10:46
@siegel86 can you please provide some better instructions as to per what needs to be done exactly?
I actually tried my best to keep the spinning to the lowest and I believe that is a feature and actually an improvement, rather than a downside. I believe we should keep the user waiting at minimal.
@kevinp if you can provide any input here, that would be great as well.

**Comment by siegel86** [comment] 2019-03-25 15:57
When I go to my cart and place my order, the current version has a "hang tight" wheel that just spins.  
![Image-1](https://user-images.githubusercontent.com/42547181/54934245-691fb200-4edb-11e9-8a92-3aeb761f880a.jpg)
I think I've figured out why it spins while testing.    If I dont have the tablet on then the order on the phone stays in the "hang tight" spin.   But if i have the tablet on, it goes into the Order Confirmed screen just as we want it.    Please confirm this is the explanation.

**Comment by siegel86** [comment] 2019-03-25 15:58
If that is the explanation then we can close out this issue.

**Comment by danipralea** [comment] 2019-03-25 16:04
that is correct @siegel86

**Closed by danipralea** 2019-03-25 16:04 UTC
