### ISSUE TITLE
Authentication/Signup:  Logout and Login flow broken?

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#70] opened 2019-03-19 17:47 UTC
When i log out and log back in and hit "Sign In" it does not take me back into the site.    I tried creating an account again with the same information and it wont let me through.  I also tried to set up a new account and it wont let me add a new account using a different email address and password (when i hit "Create Account" the button just clicks over.

**Comment by kevinp** [comment] 2019-03-22 21:43
@danipralea , would you please label as accepted if you understand the issue.  If not, please ask clarifying questions.  Once you accept, would you please add the following to the issue title:  (6, 0, 0) where first number is estimate effort in hours, second is hours worked on issue, and third is remaining hours to completion?  We'll update the project board with priority.  Let me know if you have any suggestions too on what could help from a project management perspective.  Thanks!

**Comment by danipralea** [comment] 2019-03-25 10:55
@kevinp @siegel86 is this still relevant? can you reproduce it? Because I cannot at this moment.

**Comment by kevinp** [comment] 2019-03-25 10:56
@siegel86 , closing.  Please re-open if you have futher issues.

**Closed by kevinp** 2019-03-25 10:56 UTC
Labels: bug
